### ISSUE TITLE
Can scripts downloaded from website include the narrative (not just raw code)?

### ISSUE THREAD

**Issue by ablaom** [alan-turing-institute/MLJTutorials#12]
If I download the script from the top of https://alan-turing-institute.github.io/MLJTutorials/pub/getting-started/model-tuning.html I don't get the complete narrative that goes with the script. 

Is there a reason why I don't get the full script, MLJTutorials/scripts/A-model-tuning.jl? Is this not executable?

**Comment by tlienart** [comment]
Oh, sorry this was a choice made on purpose given that the scripts are available as such in the repo; it's trivial to add a third link to the full (literate) script or even replace the "raw" script one with the full literate one; I  just  thought  that the raw one may appeal to people who would not want to  be encumbered by comments in their experimentation

**Comment by ablaom** [comment]
I vote for "add a third link (notebook, raw script, annotated script)"

**Comment by tlienart** [comment]
done in 58db031
