### ISSUE TITLE
Shuffling and use of learning_curve in crab / XGBClassifier example

### ISSUE THREAD

**Issue by ablaom** [alan-turing-institute/MLJTutorials#37]
From the learning_curve! docstring:

```julia
If using a `Holdout` `resampling` strategy, and the specified
hyperparameter is the number of iterations in some iterative model
(and that model has an appropriately overloaded `MLJBase.update`
method) then training is not restarted from scratch for each increment
of the parameter, ie the model is trained progressively.
```

So let's not use CV() in the crab example (my bad) because it would be slow if the data was really large.

Also, the data is not shuffled a priori (but ordered by target value). So we should probably just shuffle the data once and for all at the very beginning of the tutorial.

**Comment by tlienart** [comment]
I still have to  fix this
