### ISSUE TITLE
Update required in README instructions

### ISSUE THREAD

**Issue by ashryaagr** [alan-turing-institute/MLJTutorials#48]
In the README, [modifying-literate-scripts](https://github.com/alan-turing-institute/MLJTutorials/blob/master/README.md#modifying-literate-scripts) section says "add/modify tutorials in the `scripts/` folder". But it should be `_literate/` . No `scripts/` folder exists.

In the README, [visualise-modifications-locally](https://github.com/alan-turing-institute/MLJTutorials/blob/master/README.md#visualise-modifications-locally) section uses JuDoc to serve. But on using JuDoc.serve(), I get a message `JuDoc.jl is being renamed to Franklin.jl`. `JuDoc.serve()` gives "directory missing" errors which can be seen below.
![MLJTutorialsError](https://user-images.githubusercontent.com/40825065/78116742-6034bb00-7422-11ea-9ecd-baf75b836efd.png)

But `Franklin.serve()` works perfectly.
So I suggest that `JuDoc.serve()` be replaced with `Franklin.serve()`

**Comment by tlienart** [comment]
Yes! kindly open a PR with these changes, thanks!
